Capstone project
wolterbwambale/Online-Conference pull request #1
Opened 2023-03-24 21:57 UTC by wolterbwambale

I have built my capstone project  has the following:

   home page, about page. with media queries of less than 768px to a wider screen.
it has the interaction of links i.e home page and about page on both mobile and desktop versions.
The mobile menu has a close (X) button that closes the menu and   Featured speakers are created dynamically in JavaScript.

2023-03-24 23:00 UTC, mwanawabangona requested changes
Hi @wolterbwambale,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 23:00 UTC, mwanawabangona commented on README.md
>  ## 🙏 Acknowledgments <a name="acknowledgements"></a>
- [ ] `required`
- [ ] On the  "Acknowledgements" section this where  you give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). 🙏 
- [ ] Please make the changes 🥂

2023-03-24 23:00 UTC, mwanawabangona commented on index.html
> +            <span>lecture</span>
- [ ] `required`
- [ ] Please make the border-boxes same size and and aligned like the origin template.
- [ ] please see screenshot below

`your template`
![image](https://user-images.githubusercontent.com/66230306/227655532-4f42df4a-2a6f-4f8e-963d-4bc4c7bc1865.png)

`orignal template`
![image](https://user-images.githubusercontent.com/66230306/227655849-58548f2f-c84e-4fe9-966d-3e75f3693e82.png)

2023-03-24 23:00 UTC, mwanawabangona commented on index.html
> +                        </a>
- [ ] `required`
- [ ] Please make the first navbar black like the template
- [ ] also the logo should be in line with where you start the paragraph `face to face with gorillas`
- [ ] and I suggest you increase the fonts like the original template
- [ ] please screenshots below

`your template`
![image](https://user-images.githubusercontent.com/66230306/227656878-f695a422-1348-47ac-b429-95df8d63e02e.png)

`original template`
![image](https://user-images.githubusercontent.com/66230306/227657009-6e25ff75-ac11-40f2-bfb7-1098f3978263.png)

2023-03-24 23:00 UTC, mwanawabangona commented on README.md
> -- [Live Demo Link](https://google.com)
- [ ] `required`
- [ ] Please deployed your project as required.

`see the error i'm getting`
![image](https://user-images.githubusercontent.com/66230306/227657400-5dd21536-01aa-4982-b402-9b5a11367f8a.png)

2023-03-24 23:00 UTC, mwanawabangona commented on README.md
> +[Click Here for Video Presentation](https://www.loom.com/share/37fdc5ee0b2b4ab9994e54aa0f504f6a)
- [ ] `required`
- [ ] I'm a bit confused here, your profile shows you are male but the video presentation is done by a female.
- [ ] Please help me understand

2023-03-25 08:21 UTC, sumairq approved these changes
### Hi @wolterbwambale , 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-03-25 08:26 UTC, merged